name: auto-merge
on:
  pull_request_target:

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-22.04
    if: >
      github.actor == 'dependabot[bot]'
    steps:
      - id: metadata
        uses: dependabot/fetch-metadata@v2.3.0
      - name: Enable auto-merge for Dependabot PRs
        if: >
          steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: gh pr merge --auto --merge '${{ github.event.pull_request.html_url }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
